name: Create, Scan and Publish KAITO image
on:
  pull_request:
    branches:
      - main
      - release-**

permissions:
  contents: write
  packages: write


env:
  REGISTRY: ghcr.io
  GO_VERSION: '1.20'
  IMAGE_NAME: 'workspace'
  IMG_TAG: 'latest'

jobs:
  create-tag:
    runs-on: ubuntu-20.04
    outputs:
      tag: ${{ steps.get-tag.outputs.tag }}
    steps:
      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION  }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - id: get-tag
        name: Get tag
        run: echo "tag=$(echo ${{ github.event.pull_request.head.ref }} | tr -d release-)" >> $GITHUB_OUTPUT

  publish-images:
    runs-on: ubuntu-20.04
    steps:
      - name: Save registry and tag as an artifact for other workflows that run on workflow_run to download them
        run: |
          mkdir -p /tmp/artifacts
          echo ${{ github.sha }} >> /tmp/artifacts/tag.txt
          cat /tmp/artifacts/tag.txt
      - uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: /tmp/artifacts
